<project>
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.sandflow</groupId>
    <artifactId>regmxflib-root</artifactId>
    <version>1.0.1-SNAPSHOT</version>
  </parent>

  <artifactId>regmxflib-class-generator</artifactId>

  <dependencies>
    <dependency>
      <groupId>com.sandflow</groupId>
      <artifactId>regmxflib-common</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-api</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.github.jknack</groupId>
      <artifactId>handlebars</artifactId>
      <version>4.4.0</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-deploy-plugin</artifactId>
        <configuration>
          <skip>true</skip>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <configuration>
          <skip>true</skip>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>