name: Test

on: [push, pull_request]

jobs:
  java-build:

    runs-on: ubuntu-latest

    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'pull_request'

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up JDK 11 (for testing)
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'corretto'

    - name: Set up JDK 17 (for building and testing)
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven

    - name: Java 17 build and test
      run: mvn test

    - name: Java 11 Test
      run: mvn test -P runtime-test -DcompatTestJdk=11

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        load: true
        tags: regmxflib-ci-env:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Run Compatibility Tests
      run: |
        docker run --rm \
          -v $GITHUB_WORKSPACE:/workspace \
          -w /tmp \
          regmxflib-ci-env:latest \
          bash /workspace/java-library/src/test/sh/compat.sh

  cpp_build:
    name: Test C++

    runs-on: ubuntu-latest

    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'pull_request'

    steps:
    - name: install dependencies
      run: sudo apt install libxerces-c-dev
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Test C++
      run: |
        cmake -B cpp/build -S cpp
        cd cpp/build
        make
        ctest
